import {
  CITIES,
  externalId,
  floatBetween,
  GenCtx,
  intBetween,
  isoDaysFromNow,
  pick,
  rng,
} from './common'

function ymd(daysFromNow: number): string {
  const d = new Date(Date.now() + daysFromNow * 86_400_000)
  return d.toISOString().slice(0, 10)
}

function place(city: (typeof CITIES)[number]) {
  return {
    objectType: 'address',
    city: city.name,
    country: city.country.toUpperCase(),
    postalCode: city.postal,
    geoCoordinate: { latitude: city.lat, longitude: city.lon },
    geocoded: true,
  }
}

function loadingPlace(
  city: (typeof CITIES)[number],
  type: 'LOADING' | 'UNLOADING',
  dayOffset: number,
) {
  return {
    loadingType: type,
    address: place(city),
    startTime: '08:00',
    endTime: '17:00',
    earliestLoadingDate: ymd(dayOffset),
    latestLoadingDate: ymd(dayOffset + 1),
  }
}

/** TIMOCOM Freight Exchange v3 — publish freight offer body. */
export function freightOfferPublish(ctx: GenCtx) {
  const rand = rng(ctx)
  const origin = pick(rand, [...CITIES.filter((c) => c.country === 'pl')])
  const dest = pick(rand, [...CITIES.filter((c) => c.name !== origin.name)])
  const amount = floatBetween(rand, 450, 2400, 2)
  const currency = String(ctx.vars?.currency ?? 'EUR')

  return {
    objectType: 'freightOffer',
    customer: { id: Number(ctx.vars?.customerId ?? 123456) },
    contactPerson: {
      title: 'MR',
      firstName: 'Open',
      lastName: 'Mercato',
      email: String(ctx.vars?.email ?? 'timocom-sim@open-mercato.local'),
      businessPhone: '+48 22 000 00 00',
      languages: ['pl', 'en', 'de'],
    },
    freightDescription: `OM TIMOCOM sim ${externalId(ctx, 'TC')}`,
    publicRemark: 'Generated by open-mercato timocom-api-simulator',
    internalRemark: `batch=${ctx.batchId} index=${ctx.index}`,
    trackable: true,
    acceptQuotes: true,
    length_m: floatBetween(rand, 6, 13.6, 2),
    weight_t: floatBetween(rand, 5, 24, 2),
    paymentDueWithinDays: 30,
    price: { amount, currency },
    vehicleProperties: {
      type: [pick(rand, ['VEHICLE_UP_TO_12_T', 'TRAILER', 'SEMI_TRAILER'])],
      body: [pick(rand, ['CURTAIN_SIDER', 'BOX', 'MOVING_FLOOR'])],
    },
    loadingPlaces: [
      loadingPlace(origin, 'LOADING', intBetween(rand, 1, 3)),
      loadingPlace(dest, 'UNLOADING', intBetween(rand, 3, 6)),
    ],
  }
}

export function freightOfferSearch(ctx: GenCtx) {
  const rand = rng(ctx)
  const origin = pick(rand, [...CITIES])
  const dest = pick(rand, [...CITIES.filter((c) => c.name !== origin.name)])
  return {
    inclusiveRightUpperBoundDateTime: isoDaysFromNow(rand, 7, 14),
    firstResult: 0,
    maxResults: Number(ctx.vars?.maxResults ?? 30),
    startLocation: {
      objectType: 'area',
      area: {
        objectType: 'circle',
        center: { latitude: origin.lat, longitude: origin.lon },
        radius_km: Number(ctx.vars?.radiusKm ?? 50),
      },
    },
    destinationLocation: {
      objectType: 'area',
      area: {
        objectType: 'circle',
        center: { latitude: dest.lat, longitude: dest.lon },
        radius_km: Number(ctx.vars?.radiusKm ?? 80),
      },
    },
  }
}

export function vehicleSpacePublish(ctx: GenCtx) {
  const rand = rng(ctx)
  const origin = pick(rand, [...CITIES])
  return {
    objectType: 'vehicleSpaceOffer',
    customer: { id: Number(ctx.vars?.customerId ?? 123456) },
    contactPerson: {
      title: 'MR',
      firstName: 'Open',
      lastName: 'Mercato',
      email: String(ctx.vars?.email ?? 'timocom-sim@open-mercato.local'),
      businessPhone: '+48 22 000 00 00',
      languages: ['pl', 'en'],
    },
    publicRemark: `Vehicle space ${externalId(ctx, 'VS')}`,
    length_m: floatBetween(rand, 6, 13.6, 2),
    weight_t: floatBetween(rand, 8, 24, 2),
    vehicleProperties: {
      type: ['SEMI_TRAILER'],
      body: ['CURTAIN_SIDER'],
    },
    loadingPlaces: [loadingPlace(origin, 'LOADING', intBetween(rand, 1, 4))],
  }
}

export function freightOfferEvent(ctx: GenCtx) {
  return {
    event: 'timocom.freightOffer.published',
    occurred_at: new Date().toISOString(),
    source: 'timocom',
    payload: freightOfferPublish(ctx),
  }
}

export function freightQuoteCreate(ctx: GenCtx) {
  const rand = rng(ctx)
  return {
    objectType: 'freightQuote',
    freightOfferId: String(ctx.vars?.freightOfferId ?? externalId(ctx, 'FO')),
    price: {
      amount: floatBetween(rand, 400, 2000, 2),
      currency: String(ctx.vars?.currency ?? 'EUR'),
    },
    remark: `Quote from OM sim ${ctx.batchId}`,
  }
}
